-- Auto-generated by scripts/generate-seed.mjs from src/data/catalog-products.ts.
-- Do not hand-edit — re-run the script instead. Safe to re-run: uses fixed
-- ids and ON CONFLICT upserts throughout.
--
-- Seeds one demo account + a fully-populated "kleaner" catalog (the original
-- 112-item single-tenant catalogue) so the platform has a real example the
-- moment Supabase is wired up. This account has no auth user attached yet —
-- link it to yourself by inserting an account_members row for your own
-- auth.users id after you sign up, e.g.:
--   insert into account_members (account_id, user_id, role)
--   values ('00000000-0000-0000-0000-000000000001', '<your-auth-user-id>', 'owner');

insert into accounts (id, name, currency, order_email)
values ('00000000-0000-0000-0000-000000000001', 'Kleaner (Citadel Trading)', 'QAR', 'orders@kleaner.qa')
on conflict (id) do update set name = excluded.name;

insert into catalogs (id, account_id, name, slug, status, template, accent, currency, order_email)
values ('00000000-0000-0000-0000-000000000002', '00000000-0000-0000-0000-000000000001', 'Kleaner Trade Catalogue', 'kleaner', 'live', 'grid', '#0b5fce', 'QAR', 'orders@kleaner.qa')
on conflict (id) do update set name = excluded.name, status = excluded.status;

-- No "domains" row for the included subdomain: routing matches
-- {slug}.<NEXT_PUBLIC_ROOT_DOMAIN> against catalogs.slug directly (see
-- src/lib/catalog/resolve.ts), and the Admin UI reconstructs the display
-- string the same way, so a table row would just be a stale duplicate of
-- catalogs.slug the moment the root domain env var ever changes. The
-- "domains" table is used only for custom domains a tenant adds themselves.

delete from catalog_items where catalog_id = '00000000-0000-0000-0000-000000000002';
insert into catalog_items (catalog_id, code, category, name, description, price, pack, image, position, visible, barcode)
values
  ('00000000-0000-0000-0000-000000000002', 'KA2210', 'Mops & Buckets', 'Flat Mop', '40x10cm flat mop, chenille mop refill 43x13cm. 70cm-120cm telescopic metal handle.', 15.25, '', '/catalog/images/KA2210.jpg', 0, true, '6959125752759'),
  ('00000000-0000-0000-0000-000000000002', 'K19008', 'Mops & Buckets', 'Microfiber Flat Mop', 'Flat mop set size 41x10.5cm. Microfiber mop refill 75cm-130cm telescopic metal handle, dia 22/25mm.', 21.75, '', '/catalog/images/K19008.jpg', 1, true, '6959125751240'),
  ('00000000-0000-0000-0000-000000000002', 'GSA009', 'Mops & Buckets', 'Microfiber Water Mop', 'Microfiber head 140g. Metal handle 120cm / dia 21.5mm.', 9.75, '', '/catalog/images/GSA009.jpg', 2, true, '6959125750236'),
  ('00000000-0000-0000-0000-000000000002', 'GSA010', 'Mops & Buckets', 'Twist Mop', 'Microfiber mop head, 120cm metal handle, self-lock function.', 14.25, '', '/catalog/images/GSA010.jpg', 3, true, '6959125750250'),
  ('00000000-0000-0000-0000-000000000002', 'GSA030', 'Mops & Buckets', 'Non-Woven Mop Set', 'Non-woven mop head 110g yellow. 120cm metal handle. 190gsm; 22 pcs strips (2x58cm). Italy screw. Kleaner logo.', 11.5, '', '/catalog/images/GSA030.jpg', 4, true, '6959125753640'),
  ('00000000-0000-0000-0000-000000000002', 'GSA030B', 'Mops & Buckets', 'Cotton Water Mop', 'Mix cotton head 200g. Metal handle 130cm. Dia 21.5mm + American thread head.', 7.75, '', '/catalog/images/GSA030B.jpg', 5, true, '6959125751417'),
  ('00000000-0000-0000-0000-000000000002', 'K19023', 'Mops & Buckets', 'Microfiber Water Mop', 'Microfiber head 160g. Metal handle 130cm. Dia 21.5mm + American thread head.', 10.75, '', '/catalog/images/K19023.jpg', 6, true, '6959125751431'),
  ('00000000-0000-0000-0000-000000000002', 'K19024', 'Mops & Buckets', 'Twist Mop', 'Mix cotton head 300g. 130cm metal handle. Self-lock function.', 16.75, '', '/catalog/images/K19024.jpg', 7, true, '6959125751455'),
  ('00000000-0000-0000-0000-000000000002', 'K19025', 'Mops & Buckets', 'Twist Mop', 'Microfiber twist mop head. 130cm metal handle. Self-lock function.', 16.75, '', '/catalog/images/K19025.jpg', 8, true, '6959125751479'),
  ('00000000-0000-0000-0000-000000000002', 'GSA011', 'Mops & Buckets', 'Professional Cotton Mop', '60cm flat mop. Mixed cotton mop refill. 135cm metal handle (includes clip and handle grip).', 28.25, '', '/catalog/images/GSA011.jpg', 9, true, '6959125751066'),
  ('00000000-0000-0000-0000-000000000002', 'GSR-A011', 'Mops & Buckets', 'Cotton Mop Refill', 'Mixed cotton mop refill for GSA011. Size 60x16.5cm.', 11.75, '', '/catalog/images/GSR-A011.jpg', 10, true, '6959125751547'),
  ('00000000-0000-0000-0000-000000000002', 'GSA004', 'Mops & Buckets', 'PVA Magic Mop', '27cm PVA head, replaceable. 76cm-107cm telescopic stainless steel handle.', 18.75, '', '/catalog/images/GSA004.jpg', 11, true, '6959125751440'),
  ('00000000-0000-0000-0000-000000000002', 'GSA005', 'Mops & Buckets', 'PVA Magic Mop', '27cm PVA head, replaceable. 70cm-106cm telescopic stainless steel handle. Dia 2.2cm/2.5cm.', 19.25, '', '/catalog/images/GSA005.jpg', 12, true, '6959125750144'),
  ('00000000-0000-0000-0000-000000000002', 'KB2202', 'Other', 'Window Cleaner 10"', '10" cleaning head, 360 degree rotatable. 78cm-130cm telescopic aluminium handle, dia 19-22mm. Paper card packing.', 20.75, '', '/catalog/images/KB2202.jpg', 13, true, '6959125752605'),
  ('00000000-0000-0000-0000-000000000002', 'GSB008', 'Other', 'Window Cleaner', '20cm TPR scraper.', 3.25, '', '/catalog/images/GSB008.jpg', 14, true, '6959125750342'),
  ('00000000-0000-0000-0000-000000000002', 'GSC001', 'Brooms', 'Dustpan & Broom', '25.5cm dustpan. 80mm bristle. 70cm metal handle.', 11.25, '', '/catalog/images/GSC001.jpg', 15, true, '6959125750359'),
  ('00000000-0000-0000-0000-000000000002', 'K19003', 'Dustpans', 'Dustpan & Brush', '24.5cm dustpan. 50mm PET bristle. Kleaner brand.', 8.25, '', '/catalog/images/K19003.jpg', 16, true, '6959125751158'),
  ('00000000-0000-0000-0000-000000000002', 'KC2001', 'Dustpans', 'Dustpan & Brush', 'Dustpan size 315x210x80mm. 50mm bristle.', 5.75, '', '/catalog/images/KC2001.jpg', 17, true, '6959125751943'),
  ('00000000-0000-0000-0000-000000000002', 'KC2002', 'Dustpans', 'Dustpan & Brush', 'Dustpan size 360x230x105mm. 50mm bristle.', 9.5, '', '/catalog/images/KC2002.jpg', 18, true, '6959125751745'),
  ('00000000-0000-0000-0000-000000000002', 'K20004', 'Brooms', 'Dustpan & Broom', 'Foldable broom and dustpan set. Size 24x26x9cm. 90mm bristle. 72cm metal handle.', 15.5, '', '/catalog/images/K20004.jpg', 19, true, '6959125751745'),
  ('00000000-0000-0000-0000-000000000002', 'GSC009', 'Brooms', 'Dustpan & Broom Set', 'Wind-proof dustpan set. Dustpan 30x28x12cm. Broom 21x22/16cm bristle, metal handle 80cm with plastic grip. Dustpan metal handle 75cm.', 33, '', '/catalog/images/GSC009.jpg', 20, true, '6959125751981'),
  ('00000000-0000-0000-0000-000000000002', 'GSD001', 'Brushes', 'Toilet Brush & Caddy Set', 'Length 37cm. 25mm bristle. Product size 11.5x11.5x37cm.', 5, '', '/catalog/images/GSD001.jpg', 21, true, '6959125750380'),
  ('00000000-0000-0000-0000-000000000002', 'GSD006', 'Brushes', 'Toilet Brush', 'Length 49.5cm. 32mm bristle.', 6, '', '/catalog/images/GSD006.jpg', 22, true, '6959125750434'),
  ('00000000-0000-0000-0000-000000000002', 'KD2205', 'Brushes', 'Toilet Brush', 'Total length 36cm. 23mm bristle.', 6, '', '/catalog/images/KD2205.jpg', 23, true, '6959125752469'),
  ('00000000-0000-0000-0000-000000000002', 'KH2301', 'Brushes', 'Plunger', 'Material PP & TPE. 2-section plastic handle, total length 43cm. TPE sucker dia 15cm. Weight 220g.', 7, '', '/catalog/images/KH2301.jpg', 24, true, '6959125752988'),
  ('00000000-0000-0000-0000-000000000002', 'KD2411', 'Brushes', 'Toilet Brush & Plunger Set', 'Total length 47cm. 25mm PP bristle. 15cm TPR sucker.', 19, '', '/catalog/images/KD2411.jpg', 25, true, '6959125753749'),
  ('00000000-0000-0000-0000-000000000002', 'KD2103', 'Brushes', 'Cup Brush', 'Plastic handle 28.5cm with logo. Scouring pad + sponge 10x4.5cm, 3cm thick. OPP bag packing.', 2, '', '/catalog/images/KD2103.jpg', 26, true, '6959125752384'),
  ('00000000-0000-0000-0000-000000000002', 'KD2104', 'Brushes', 'Dish Brush', 'Material PP+TPR. Size 5.5x8x10.5cm. 3cm bristle.', 4.25, '', '/catalog/images/KD2104.jpg', 27, true, '6959125752421'),
  ('00000000-0000-0000-0000-000000000002', 'KD2101', 'Other', 'Soap Dispensing Dish Wand', 'Dish brush size 26x4x8.5cm. 3cm bristle. Plastic handle and brush head. Paper card packing.', 6.25, '', '/catalog/images/KD2101.jpg', 28, true, '6959125752087'),
  ('00000000-0000-0000-0000-000000000002', 'KD2102', 'Other', 'Soap Dispensing Dish Wand', 'Dish brush size 26x4x8.5cm. Plastic handle and sponge head. Paper card packing.', 6.25, '', '/catalog/images/KD2102.jpg', 29, true, '6959125752100'),
  ('00000000-0000-0000-0000-000000000002', 'K19014', 'Brushes', 'Toilet Brush & Caddy Set', 'Length 36cm. 29mm bristle. TPR handle. Plastic base.', 11.25, '', '/catalog/images/K19014.jpg', 30, true, '6959125751325'),
  ('00000000-0000-0000-0000-000000000002', 'K19016', 'Brushes', 'Dish Brush', 'Length 26.5cm. 25mm bristle. TPR handle.', 5, '', '/catalog/images/K19016.jpg', 31, true, '6959125751349'),
  ('00000000-0000-0000-0000-000000000002', 'K19017', 'Brushes', 'Dish Brush', 'Length 26cm. 25mm bristle. TPR handle.', 5, '', '/catalog/images/K19017.jpg', 32, true, '6959125751356'),
  ('00000000-0000-0000-0000-000000000002', 'K19018', 'Brushes', 'Brush', 'Size 16.8x7.4cm. 25mm bristle.', 6, '', '/catalog/images/K19018.jpg', 33, true, '6959125751363'),
  ('00000000-0000-0000-0000-000000000002', 'K19020', 'Brushes', 'Brush', 'Size 15.5x7.5cm. 27mm bristle. TPR grip.', 7.5, '', '/catalog/images/K19020.jpg', 34, true, '6959125751387'),
  ('00000000-0000-0000-0000-000000000002', 'GSE001', 'Cloths & Dusters', 'PP Duster', 'PP bristle head 40cm. Bendable cleaning head.', 4.5, '', '/catalog/images/GSE001.jpg', 35, true, '6959125750564'),
  ('00000000-0000-0000-0000-000000000002', 'GSE002', 'Cloths & Dusters', 'Microfiber Duster', 'Microfiber head 35cm. Bendable cleaning head. 80cm-120cm telescopic aluminum handle.', 15, '', '/catalog/images/GSE002.jpg', 36, true, '6959125750571'),
  ('00000000-0000-0000-0000-000000000002', 'GSG003', 'Cloths & Dusters', 'Microfiber Cloths 2pcs', 'Size 38x40cm. 80% polyester, 20% polyamide. 2pc / 3 color mix per carton.', 5, '', '/catalog/images/GSG003.jpg', 37, true, '6959125750601'),
  ('00000000-0000-0000-0000-000000000002', 'GSG004', 'Cloths & Dusters', 'Microfiber Cloths 4pcs', 'Size 38x40cm. 80% polyester, 20% polyamide. 4pc / 3 color mix per carton.', 8, '', '/catalog/images/GSG004.jpg', 38, true, '6959125750618'),
  ('00000000-0000-0000-0000-000000000002', 'GSG005', 'Cloths & Dusters', 'Microfiber Cloths 6pcs', 'Size 38x40cm. 80% polyester, 20% polyamide. 6pc / 6 color mix per carton.', 12, '', '/catalog/images/GSG005.jpg', 39, true, '6959125750625'),
  ('00000000-0000-0000-0000-000000000002', 'GSG006', 'Cloths & Dusters', 'Microfiber Cloths 8pcs', 'Size 30x30cm. 80% polyester, 20% polyamide. 8pcs / 4 color mix per carton.', 10.5, '', '/catalog/images/GSG006.jpg', 40, true, '6959125750632'),
  ('00000000-0000-0000-0000-000000000002', 'GSG008', 'Cloths & Dusters', 'Non-Woven Cloths 6pcs', 'Non-woven cloths, size 38x40cm. 50% viscose + 50% polyester. OPP bag 6pc/bag. 120g/gsm, 3 color mix.', 5.5, '', '/catalog/images/GSG008.jpg', 41, true, '6959125750656'),
  ('00000000-0000-0000-0000-000000000002', 'GSG009', 'Cloths & Dusters', 'Non-Woven Cloths 10pcs', 'Non-woven cloths, size 31x35cm. 100gsm, 50% viscose + 50% polyester. 10pcs/bag, 5 color mix.', 5.5, '', '/catalog/images/GSG009.jpg', 42, true, '6959125750663'),
  ('00000000-0000-0000-0000-000000000002', 'GSG010', 'Scourers & Sponges', 'Cellulose Sponge 5pcs', 'Size 18x20cm. 5pcs/pack. PP bag.', 7.5, '', '/catalog/images/GSG010.jpg', 43, true, '6959125750670'),
  ('00000000-0000-0000-0000-000000000002', 'GSG011', 'Cloths & Dusters', 'Kitchen Towel', 'Size 30x30cm. 3pcs/pack. 23g, 4 layer.', 4, '', '/catalog/images/GSG011.jpg', 44, true, '6959125750786'),
  ('00000000-0000-0000-0000-000000000002', 'GSG015', 'Cloths & Dusters', 'Microfiber Cloths 10pcs', '70% polyester + 30% polyamide, blue, size 35x35cm. 10pcs/bag, 400gsm, 50g/pc, 24bags/ctn.', 19.25, '', '/catalog/images/GSG015.jpg', 45, true, '6959125753008'),
  ('00000000-0000-0000-0000-000000000002', 'GSH001', 'Scourers & Sponges', 'Sponge Scourer 6pcs', 'Scouring pad, size 13x9cm. 6pcs/pack.', 4, '', '/catalog/images/GSH001.jpg', 46, true, '6959125750687'),
  ('00000000-0000-0000-0000-000000000002', 'GSH002', 'Scourers & Sponges', 'Sponge Scourer 5pcs', 'Size 10x5.3x3cm/pc. 5pcs/bag.', 2.5, '', '/catalog/images/GSH002.jpg', 47, true, '6959125750694'),
  ('00000000-0000-0000-0000-000000000002', 'GSH003', 'Scourers & Sponges', 'Sponge Scourer', 'Size 9x5.8x3cm/pc. 10pcs/bag.', 5.25, '', '/catalog/images/GSH003.jpg', 48, true, '6959125750700'),
  ('00000000-0000-0000-0000-000000000002', 'GSH004', 'Cloths & Dusters', 'Latex Gloves', '2 pair/OPP bag. L size, 37g x 2 pair. Orange/yellow mix.', 4.75, '', '/catalog/images/GSH004.jpg', 49, true, '6959125750717'),
  ('00000000-0000-0000-0000-000000000002', 'GSH007', 'Scourers & Sponges', 'Stainless Steel Scourer 2pcs', 'Stainless steel, 2x15g/OPP.', 1.25, '', '/catalog/images/GSH007.jpg', 50, true, '6959125750748'),
  ('00000000-0000-0000-0000-000000000002', 'GSH008', 'Scourers & Sponges', 'Stainless Steel Scourer 4pcs', 'Stainless steel, 4x15g/OPP.', 2.25, '', '/catalog/images/GSH008.jpg', 51, true, '6959125750755'),
  ('00000000-0000-0000-0000-000000000002', 'GSH009', 'Scourers & Sponges', 'Stainless Steel Scourer 6pcs', 'Stainless steel, 6x15g/OPP.', 3.25, '', '/catalog/images/GSH009.jpg', 52, true, '6959125750762'),
  ('00000000-0000-0000-0000-000000000002', 'GSH010', 'Scourers & Sponges', 'Stainless Steel Scourer 12pcs', 'Stainless steel, 12pcs x 15g. Paper card packing.', 8.5, '', '/catalog/images/GSH010.jpg', 53, true, '6959125750779'),
  ('00000000-0000-0000-0000-000000000002', 'GSH011', 'Scourers & Sponges', 'Sponge Scouring Pad 6pcs/Set', 'Size 10x6.5x3cm. 6pcs/set.', 4.5, '', '/catalog/images/GSH011.jpg', 54, true, '6959125751141'),
  ('00000000-0000-0000-0000-000000000002', 'GSH012', 'Scourers & Sponges', 'Sponge Scouring Pad', 'Size 9.3x7x4.2cm. 3pcs/pack.', 3, '', '/catalog/images/GSH012.jpg', 55, true, '6959125751080'),
  ('00000000-0000-0000-0000-000000000002', 'GSH018', 'Scourers & Sponges', 'Cellulose Scouring Pad 6pcs', 'Cellulose sponge scouring pad. Size 11x7x2cm. 6pcs/pack; 4packs/inner bag.', 8.5, '', '/catalog/images/GSH018.jpg', 56, true, '6959125752957'),
  ('00000000-0000-0000-0000-000000000002', 'GSF001', 'Scourers & Sponges', 'Sponge Scourer', 'Size 14.5x9.5x1.7cm. 12pcs/set, each packed in one OPP bag.', 19, '', '/catalog/images/GSF001.jpg', 57, true, '6959125751677'),
  ('00000000-0000-0000-0000-000000000002', 'GSF002', 'Scourers & Sponges', 'Sponge Scourer', 'Size 13x9x1.7cm. 12pcs/set, each packed in one OPP bag.', 11.25, '', '/catalog/images/GSF002.jpg', 58, true, '6959125751684'),
  ('00000000-0000-0000-0000-000000000002', 'GSH013', 'Scourers & Sponges', 'PP Scourer', 'Double sponge. Sponge size 6.5x7x7cm. Handle length 22.5cm.', 3.25, '', '/catalog/images/GSH013.jpg', 59, true, '6959125751691'),
  ('00000000-0000-0000-0000-000000000002', 'GSH014', 'Scourers & Sponges', 'PP Scourer', 'PET scourer. Size 9x9x7cm. 5pcs/set.', 10.75, '', '/catalog/images/GSH014.jpg', 60, true, '6959125751707'),
  ('00000000-0000-0000-0000-000000000002', 'GSH015', 'Brushes', 'Bath Brush', 'Scouring brush 7.3x14cm, pad 9x15cm. 3 colors per set. Plastic brush holder. Paper card packing.', 6, '', '/catalog/images/GSH015.jpg', 61, true, '6959125752216'),
  ('00000000-0000-0000-0000-000000000002', 'KH2402', 'Brushes', 'Tub & Tile Scrubber', 'Scouring brush 14x8cm, pad 15x9x2cm. 3pcs/set, grey. Plastic brush holder. Paper card packing.', 6.5, '', '/catalog/images/KH2402.jpg', 62, true, '6959125753695'),
  ('00000000-0000-0000-0000-000000000002', 'GSH016', 'Scourers & Sponges', 'Magic Sponge', 'Size 11x6.5x3cm. White melamine sponge 2.5cm + blue sponge 0.5cm. 5pcs/bag, 6bags/inner bag.', 3.5, '', '/catalog/images/GSH016.jpg', 63, true, '6959125752285'),
  ('00000000-0000-0000-0000-000000000002', 'GSW003', 'Scourers & Sponges', 'Microfiber Sponge', 'Oval-shaped sponge, size 23x12x5cm.', 6, '', '/catalog/images/GSW003.jpg', 64, true, '6959125750946'),
  ('00000000-0000-0000-0000-000000000002', 'GSW005', 'Cloths & Dusters', 'Chenille Glove', 'Size 24x16cm. Microfiber glove, double side use.', 7.25, '', '/catalog/images/GSW005.jpg', 65, true, '6959125750960'),
  ('00000000-0000-0000-0000-000000000002', 'GSW008', 'Cloths & Dusters', 'Wiping Cloth', 'Microfibre towel, size 40x40cm. 4pcs/pack.', 8.75, '', '/catalog/images/GSW008.jpg', 66, true, '6959125750991'),
  ('00000000-0000-0000-0000-000000000002', 'GSW009', 'Cloths & Dusters', 'Chenille Duster', 'Size 41x6cm.', 7.5, '', '/catalog/images/GSW009.jpg', 67, true, '6959125751004'),
  ('00000000-0000-0000-0000-000000000002', 'GSW010', 'Cloths & Dusters', 'Chenille Duster', 'Size 56x6cm.', 8.5, '', '/catalog/images/GSW010.jpg', 68, true, '6959125751011'),
  ('00000000-0000-0000-0000-000000000002', 'GSW011', 'Other', 'Chenille Cleaner', 'Head size 26x17.5cm. 3-section telescopic aluminium handle, size 51.5-110cm.', 20.75, '', '/catalog/images/GSW011.jpg', 69, true, '6959125751028'),
  ('00000000-0000-0000-0000-000000000002', 'GSW013', 'Scourers & Sponges', 'Sponge', 'Net sponge pad, three color. Size 14x7.8x3.3cm/pc. 3pcs/pack, 30g/pc.', 6, '', '/catalog/images/GSW013.jpg', 70, true, '6959125752049'),
  ('00000000-0000-0000-0000-000000000002', 'GSF003', 'Scourers & Sponges', 'Sponge Scourer', 'Size 12.5x9x1.7cm. 3pcs/pack, 12packs/inner bag.', 2.5, '', '/catalog/images/GSF003.jpg', 71, true, '6959125753152'),
  ('00000000-0000-0000-0000-000000000002', 'GSF004', 'Scourers & Sponges', 'Sponge Scourer', 'Size 10.5x9x1.8cm. 3pcs/pack, 12packs/inner bag.', 3.75, '', '/catalog/images/GSF004.jpg', 72, true, '6959125753169'),
  ('00000000-0000-0000-0000-000000000002', 'GSF005', 'Scourers & Sponges', 'Sponge Scourer', '2-in-1 sponge scourer, all-purpose.', 4.25, '', '/catalog/images/GSF005.jpg', 73, true, '6959125753176'),
  ('00000000-0000-0000-0000-000000000002', 'GSF007', 'Scourers & Sponges', 'Sponge Scourer', 'Size 14x10x1cm. 2pcs/bag, 12pcs/inner bag.', 3.75, '', '/catalog/images/GSF007.jpg', 74, true, '6959125753688'),
  ('00000000-0000-0000-0000-000000000002', 'KK2415', 'Brooms', 'Sponge Broom', 'Sponge broom 38x16x4cm. 72.5cm-125cm telescopic metal handle.', 15.25, '', '/catalog/images/KK2415.jpg', 75, true, '6959125753633'),
  ('00000000-0000-0000-0000-000000000002', 'K19010', 'Brooms', 'Anti-Dust Broom', 'Size 29.5x5.2cm, bristle 6.5cm, sponge 28.5x5cm, thickness 1.4cm. TPR cover both sides. Metal handle total length 131cm, dia 25mm.', 15.75, '', '/catalog/images/K19010.jpg', 76, true, '6959125751288'),
  ('00000000-0000-0000-0000-000000000002', 'GSK003', 'Brooms', 'Outdoor Broom', 'Plastic part size 27x11.8cm. 10cm bristle. 118cm metal handle.', 10.5, '', '/catalog/images/GSK003.jpg', 77, true, '6959125750823'),
  ('00000000-0000-0000-0000-000000000002', 'GSK004', 'Brooms', 'Outdoor Broom', 'Plastic part size 22.5x17.5cm. 15cm bristle. 120cm metal handle.', 13, '', '/catalog/images/GSK004.jpg', 78, true, '6959125750830'),
  ('00000000-0000-0000-0000-000000000002', 'GSK006', 'Brooms', 'Broom', '27cm broom head, Italy screw. 9cm bristle. 130cm metal handle.', 10.75, '', '/catalog/images/GSK006.jpg', 79, true, '6959125751493'),
  ('00000000-0000-0000-0000-000000000002', 'K20001', 'Brooms', 'Anti-Dust Broom', '25cm broom head, Italy screw. 9cm bristle. 2-in-1 anti-dust design. 120cm metal handle.', 11.5, '', '/catalog/images/K20001.jpg', 80, true, '6959125751714'),
  ('00000000-0000-0000-0000-000000000002', 'K20002', 'Brooms', 'Anti-Dust Broom', '27cm broom head, Italy screw PP. 11cm bristle. 130cm metal handle.', 12.5, '', '/catalog/images/K20002.jpg', 81, true, '6959125751721'),
  ('00000000-0000-0000-0000-000000000002', 'K20003', 'Brooms', 'Anti-Dust Broom', '31cm broom head, Italy screw. 10cm bristle. 130cm metal handle.', 11.75, '', '/catalog/images/K20003.jpg', 82, true, '6959125751738'),
  ('00000000-0000-0000-0000-000000000002', 'KK2304', 'Brooms', 'Broom', '130cm metal handle, Italy screw. Broom head width 33cm, 10.5cm bristle.', 11.5, '', '/catalog/images/KK2304.jpg', 83, true, '6959125753060'),
  ('00000000-0000-0000-0000-000000000002', 'KK2309', 'Brooms', 'Dustpan & Broom Set', '33cm dustpan, Italy screw. 9.5cm bristle. 130cm metal handle. Removable foam blade.', 20.25, '', '/catalog/images/KK2309.jpg', 84, true, '6959125753190'),
  ('00000000-0000-0000-0000-000000000002', 'KK2310', 'Brooms', 'Dustpan & Broom Set', '34cm dustpan, Italy screw. 17-18cm bristle. 130cm metal handle.', 22.5, '', '/catalog/images/KK2310.jpg', 85, true, '6959125753206'),
  ('00000000-0000-0000-0000-000000000002', 'KK2311', 'Brooms', 'Broom', '10.5cm bristle, Italy screw. 130cm metal handle. Removable foam blade.', 16, '', '/catalog/images/KK2311.jpg', 86, true, '6959125753213'),
  ('00000000-0000-0000-0000-000000000002', 'GSK013', 'Brooms', 'Broom', 'Triangular broom with TPR edge protection, Italy screw. Size 25x4.5cm, bristle length 10cm. 120cm metal handle. Paper card packing.', 11.5, '', '/catalog/images/GSK013.jpg', 87, true, '6959125753251'),
  ('00000000-0000-0000-0000-000000000002', 'KK2312', 'Brooms', 'Broom', '13cm PP bristle. 100cm metal handle, dia 19mm. Italy screw.', 8, '', '/catalog/images/KK2312.jpg', 88, true, '6959125753220'),
  ('00000000-0000-0000-0000-000000000002', 'KK2001', 'Brushes', 'Floor Brush', 'Size 22x7.5cm, grey bristle 4cm. Metal handle total length 120cm, dia 21.5mm.', 11.5, '', '/catalog/images/KK2001.jpg', 89, true, '6959125751967'),
  ('00000000-0000-0000-0000-000000000002', 'KK2002', 'Brushes', 'Floor Brush', 'Size 26x7.5cm, grey bristle 4cm. Metal handle total length 120cm, dia 21.5mm.', 11.5, '', '/catalog/images/KK2002.jpg', 90, true, '6959125751974'),
  ('00000000-0000-0000-0000-000000000002', 'K19004', 'Other', 'Multi-Purpose Cleaner', 'Plastic brush, Italy screw. Size 23x17x5cm, 30mm PP bristle. Metal handle length 70-120cm, dia 19/21.5mm.', 13.5, '', '/catalog/images/K19004.jpg', 91, true, '6959125751172'),
  ('00000000-0000-0000-0000-000000000002', 'K19002', 'Squeegees', 'Floor Squeegee', '42cm plastic head, double-use scraper (EVA+rubber blade). Metal handle 130cm, dia 21.5mm.', 13, '', '/catalog/images/K19002.jpg', 92, true, '6959125751110'),
  ('00000000-0000-0000-0000-000000000002', 'KK2003', 'Squeegees', 'Floor Squeegee Set', 'Floor squeegee set with metal handle.', 8.5, '', '/catalog/images/KK2003.jpg', 93, true, '6959125751998'),
  ('00000000-0000-0000-0000-000000000002', 'KK2308', 'Squeegees', 'Floor Squeegee', '120cm metal handle. 40cm TPR squeegee head. Paper card packing.', 8.5, '', '/catalog/images/KK2308.jpg', 94, true, '6959125753138'),
  ('00000000-0000-0000-0000-000000000002', 'GSK005', 'Squeegees', 'Floor Squeegee', '42cm plastic head, EVA scraper with clip design. Metal handle 120cm, dia 21.5mm + American screw head.', 11.5, '', '/catalog/images/GSK005.jpg', 95, true, '6959125750847'),
  ('00000000-0000-0000-0000-000000000002', 'GSK008', 'Squeegees', 'Floor Squeegee', '33cm plastic head, EVA scraper with clip design. Metal handle 120cm, dia 21.5mm + American screw head.', 10, '', '/catalog/images/GSK008.jpg', 96, true, '6959125751592'),
  ('00000000-0000-0000-0000-000000000002', 'GSK009', 'Squeegees', 'Floor Squeegee', '53cm plastic head, EVA scraper with clip design. Metal handle 120cm, dia 21.5mm + American screw head.', 13, '', '/catalog/images/GSK009.jpg', 97, true, '6959125751615'),
  ('00000000-0000-0000-0000-000000000002', 'KK2305', 'Squeegees', 'EVA Floor Squeegee 34cm', '34cm EVA scraper, American screw. 120cm metal handle. Kleaner logo.', 9.75, '', '/catalog/images/KK2305.jpg', 98, true, '6959125753077'),
  ('00000000-0000-0000-0000-000000000002', 'KK2307', 'Squeegees', 'EVA Floor Squeegee 54cm', '54cm EVA scraper, American screw. 120cm metal handle. Kleaner logo.', 11.25, '', '/catalog/images/KK2307.jpg', 99, true, '6959125753121'),
  ('00000000-0000-0000-0000-000000000002', 'KK2413-H', 'Squeegees', 'EVA Floor Squeegee 35cm Head', '35cm EVA scraper. Kleaner logo.', 10, '', '/catalog/images/KK2413-H.jpg', 100, true, '6959125753480'),
  ('00000000-0000-0000-0000-000000000002', 'KK2414-H', 'Squeegees', 'EVA Floor Squeegee 45cm Head', '45cm EVA scraper. Kleaner logo.', 11, '', '/catalog/images/KK2414-H.jpg', 101, true, '6959125753466'),
  ('00000000-0000-0000-0000-000000000002', 'KT2412', 'Mops & Buckets', 'Bucket with Wringer', '15L bucket with wringer, metal grip, 770g. Kleaner logo. Size 39x28.5x27cm.', 22, '', '/catalog/images/KT2412.jpg', 102, true, '6959125753442'),
  ('00000000-0000-0000-0000-000000000002', 'KA2314', 'Mops & Buckets', 'Microfiber Flat Mop', 'Mop size 37x13.2cm, includes 1 microfiber mop refill. 75cm-130cm telescopic metal handle, dia 21.5/25mm. Paper card packing.', 21.75, '', '/catalog/images/KA2314.jpg', 103, true, '6959125753336'),
  ('00000000-0000-0000-0000-000000000002', 'R-KA2314', 'Mops & Buckets', 'Microfiber Mop Refill 38cm', 'Size 38x15cm, loop yarn length 3cm, pocket style. Paper card + OPP bag packing. 24pcs/ctn.', 7.25, '', '/catalog/images/R-KA2314.jpg', 104, true, '6959125753763'),
  ('00000000-0000-0000-0000-000000000002', 'KA2315', 'Mops & Buckets', 'Microfiber Flat Mop', 'Mop size 47x13.2cm, includes 1 microfiber mop refill. 75cm-130cm telescopic metal handle, dia 21.5/25mm. Paper card packing.', 25.25, '', '/catalog/images/KA2315.jpg', 105, true, '6959125753343'),
  ('00000000-0000-0000-0000-000000000002', 'R-KA2315', 'Mops & Buckets', 'Microfiber Mop Refill 48cm', 'Size 48x15cm, loop yarn length 3cm, pocket style. Paper card + OPP bag packing. 24pcs/ctn.', 9.5, '', '/catalog/images/R-KA2315.jpg', 106, true, '6959125753770'),
  ('00000000-0000-0000-0000-000000000002', 'GSG023', 'Cloths & Dusters', 'Floor Cloths', 'Non-woven cloths for floor squeegee. Size 40x60cm, 50% viscose + 50% polyester, 250gsm. 2pcs/bag, yellow.', 8.75, '', '/catalog/images/GSG023.jpg', 107, true, '6959125753565'),
  ('00000000-0000-0000-0000-000000000002', 'GSG024', 'Cloths & Dusters', 'Floor Cloths', 'Non-woven cloths for floor squeegee. Size 50x60cm, 50% viscose + 50% polyester, 250gsm. 2pcs/bag, yellow.', 10.5, '', '/catalog/images/GSG024.jpg', 108, true, '6959125753572'),
  ('00000000-0000-0000-0000-000000000002', 'KK2306', 'Squeegees', 'EVA Floor Squeegee 43cm', '43cm EVA scraper, American screw. 120cm metal handle. Kleaner logo.', 10.75, '', '/catalog/images/KK2306.jpg', 109, true, '6959125753091'),
  ('00000000-0000-0000-0000-000000000002', 'GSG025', 'Cloths & Dusters', 'Floor Cloths', 'Non-woven cloths for floor squeegee. Size 60x60cm, 50% viscose + 50% polyester, 250gsm. 2pcs/bag, yellow.', 12, '', '/catalog/images/GSG025.jpg', 110, true, '6959125753589'),
  ('00000000-0000-0000-0000-000000000002', 'KA2418', 'Mops & Buckets', 'Electrostatic Mop Set', 'Electrostatic mop with non-woven cloths. 4-section metal handle, length 120cm, dia 21mm. Mop head 26.5x11.8cm. 20pcs dry non-woven cloths included. Colorful box packing.', 18.75, '', '/catalog/images/KA2418.jpg', 111, true, '6959125753626');
