#!/usr/bin/env node
// Regenerates supabase/seed.sql from src/data/catalog-products.ts.
// Run with: node scripts/generate-seed.mjs
//
// The 112 Kleaner products become the seed data for a demo "kleaner" tenant
// (account + catalog + domain + items) so the platform has one real,
// fully-populated example the moment Supabase is wired up.

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");

const source = readFileSync(join(root, "src/data/catalog-products.ts"), "utf8");
const lines = source.split("\n").filter((l) => l.trim().startsWith('{"code"'));
const products = lines.map((line) => JSON.parse(line.trim().replace(/,$/, "")));

if (products.length === 0) {
  console.error("No products parsed from catalog-products.ts — aborting.");
  process.exit(1);
}

// Same coarse grouping the old single-tenant UI used, kept here only for
// seeding a nicely-sectioned demo catalog. New tenants created through the
// builder don't get this — see src/components/templates/Grid.tsx.
const GROUP_RULES = [
  { group: "Mops & Buckets", keywords: ["mop", "bucket"] },
  { group: "Brooms", keywords: ["broom"] },
  { group: "Dustpans", keywords: ["dustpan"] },
  { group: "Brushes", keywords: ["brush", "plunger", "scrubber"] },
  { group: "Scourers & Sponges", keywords: ["scourer", "scouring", "sponge"] },
  { group: "Cloths & Dusters", keywords: ["cloth", "duster", "towel", "glove"] },
  { group: "Squeegees", keywords: ["squeegee"] },
];
function groupFor(category) {
  const lower = category.toLowerCase();
  for (const rule of GROUP_RULES) {
    if (rule.keywords.some((k) => lower.includes(k))) return rule.group;
  }
  return "Other";
}

function sqlString(value) {
  return `'${String(value).replace(/'/g, "''")}'`;
}

const ACCOUNT_ID = "00000000-0000-0000-0000-000000000001";
const CATALOG_ID = "00000000-0000-0000-0000-000000000002";

const itemValues = products
  .map((p, i) => {
    const position = i;
    return `  (${sqlString(CATALOG_ID)}, ${sqlString(p.code)}, ${sqlString(groupFor(p.category))}, ${sqlString(p.category)}, ${sqlString(p.description)}, ${p.price}, '', ${sqlString(p.image)}, ${position}, true, ${sqlString(p.barcode)})`;
  })
  .join(",\n");

const sql = `-- Auto-generated by scripts/generate-seed.mjs from src/data/catalog-products.ts.
-- Do not hand-edit — re-run the script instead. Safe to re-run: uses fixed
-- ids and ON CONFLICT upserts throughout.
--
-- Seeds one demo account + a fully-populated "kleaner" catalog (the original
-- 112-item single-tenant catalogue) so the platform has a real example the
-- moment Supabase is wired up. This account has no auth user attached yet —
-- link it to yourself by inserting an account_members row for your own
-- auth.users id after you sign up, e.g.:
--   insert into account_members (account_id, user_id, role)
--   values ('${ACCOUNT_ID}', '<your-auth-user-id>', 'owner');

insert into accounts (id, name, currency, order_email)
values (${sqlString(ACCOUNT_ID)}, 'Kleaner (Citadel Trading)', 'QAR', 'orders@kleaner.qa')
on conflict (id) do update set name = excluded.name;

insert into catalogs (id, account_id, name, slug, status, template, accent, currency, order_email)
values (${sqlString(CATALOG_ID)}, ${sqlString(ACCOUNT_ID)}, 'Kleaner Trade Catalogue', 'kleaner', 'live', 'grid', '#0b5fce', 'QAR', 'orders@kleaner.qa')
on conflict (id) do update set name = excluded.name, status = excluded.status;

-- No "domains" row for the included subdomain: routing matches
-- {slug}.<NEXT_PUBLIC_ROOT_DOMAIN> against catalogs.slug directly (see
-- src/lib/catalog/resolve.ts), and the Admin UI reconstructs the display
-- string the same way, so a table row would just be a stale duplicate of
-- catalogs.slug the moment the root domain env var ever changes. The
-- "domains" table is used only for custom domains a tenant adds themselves.

delete from catalog_items where catalog_id = ${sqlString(CATALOG_ID)};
insert into catalog_items (catalog_id, code, category, name, description, price, pack, image, position, visible, barcode)
values
${itemValues};
`;

writeFileSync(join(root, "supabase/seed.sql"), sql);
console.log(`Wrote supabase/seed.sql with ${products.length} items.`);
